### ISSUE TITLE
Wrong default for `LCD_LAYER_0_ADDRESS` and `LCD_LAYER_1_ADDRESS`

### ISSUE THREAD

**Issue by tronical** [STMicroelectronics/stm32h747i-disco#4]
**Describe the bug (skip if none)**

The defaults for `LCD_LAYER_0_ADDRESS` and `LCD_LAYER_1_ADDRESS` in `stm32h747i_discovery_conf_template.h` are 

https://github.com/STMicroelectronics/stm32h747i-disco-bsp/blob/bb81c6532fcc301fc760a98f8a42acede46bea83/stm32h747i_discovery_conf_template.h#L39

`0xC0000000U` and `0xC0200000U`. That's by default not a mapped memory region.

The intention was most likely to default to the SDRAM region that's at `0xD0000000` as per https://github.com/STMicroelectronics/stm32h747i-disco-bsp/blob/bb81c6532fcc301fc760a98f8a42acede46bea83/stm32h747i_discovery_sdram.h#L63

This also matches RM0433 (2.3.2).

The effect of these (IMO wrong) defaults is that out of the box the default layer initialised by `BSP_LCD_Init`/`BSP_LCD_InitEx` is at the wrong address and any layer access results in a memory fault.

I'd be happy to make a PR to correct these, but I wanted to check first that I'm not missing anything :)

**Comment by ASEHSTM** [comment]
Hello @tronical,

Thank you for your report. We have not encountered any issues with these definitions in our examples. According to the reference manual, the 0xC0000000 region (SDRAM Bank 1) is valid for use.
Could you please specify if you detected a problem with these LCD layer definitions during execution, or if it was identified through a visual check?

Thank you in advance for your cooperation.

With Regards.

**Comment by tronical** [comment]
Hi,

I encountered this problem during execution. The symptom is a memory fault.

To reproduce: generate a new template with CubeMX for this board, add the BSP, call the LCD init functions, then try to write to the layer address. It crashes.

While the current value may be valid _if_ something is mapped there, the BSP in this report defaults to mapping the SD-RAM to 0xD.

Also note how _all_ examples that use the lcd functions of this BSP also end up with 0xD.

**Comment by ASEHSTM** [comment]
Hello @tronical,

Thank you for bringing this to our attention. You are right, this issue will be fixed soon.
ST Internal Reference: 187832

With Regards,

**Comment by ASEHSTM** [comment]
Fixed in :  22c0c54
